### ISSUE TITLE
Test cases are missing

### ISSUE THREAD

**Issue by Maha-Shawky** [Moon04/charts-app#1]
The 2 test cases in the assignment not covered:
- Chart is added successfully to the dashboard view after pressing add chart.
- If something went wrong and the api responded with 500 status code, an alert should be displayed with “Something wrong happened, please try again.

Please Use any end to end testing framework (testcafe, cypress or anything else) to cover them

**Comment by Moon04** [comment]
issue solved, you may check the last commit it includes test cases for both happy scenario and internal server error scenario.
kindly, let me know if you have any comments or feedback.

**Comment by Maha-Shawky** [comment]
Are you sure you pushed this commit, I didn't find it 
This is the last [commit](https://github.com/Moon04/charts-app/commit/5e5dc2273ee73084fa7dfc446978daabee547292)

**Comment by Moon04** [comment]
I'm very sorry Maha, it's my fault I thought all changes are pushed but I checked it now and I found that it's committed but not pushed. I'm really sorry, you can check it now, and here's the [commit](https://github.com/Moon04/charts-app/commit/78c602418a6c74e3593385e0a03576e83a9e1b47)
I'd appreciate it if you told me whether these are the required test cases or there's something missing.
and it'd be great if you gave me feedback regarding the whole app in general.

**Comment by Maha-Shawky** [comment]
Thanks Mona, you did a good effort in your task, I have one feedback, always check the requirements before concentrating in the solution, because you may did great effort in non required things or miss the required things, I'll give you example
- read/save/parse csv or json files wasn't required
- e2e (end to end) two test cases are required, while more unit and integration test cases were submitted


But as I told you, you did a good job :+1:
